[build]
builder = "nixpacks"

[deploy]
startCommand = "node advanced-server.js"
healthcheckPath = "/status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 