services:
  - type: web
    name: iss-live-background
    env: node
    buildCommand: npm install
    startCommand: node advanced-server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 