services:
  - type: web
    name: iss-live-background
    env: node
    buildCommand: |
      # 시스템 패키지 업데이트 및 FFmpeg 설치
      apt-get update && apt-get install -y ffmpeg python3-pip
      # yt-dlp 설치
      pip3 install yt-dlp
      # Node.js 의존성 설치
      npm install
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: https://centrifugal-island.nyc,https://www.centrifugal-island.nyc
      - key: ISS_UPDATE_INTERVAL
        value: 5000
      - key: ISS_TIMEOUT
        value: 20000
    plan: free
    healthCheckPath: /status
    autoDeploy: true
    # WebSocket 지원을 위한 설정
    headers:
      - path: /*
        name: Upgrade
        value: websocket
      - path: /*
        name: Connection
        value: Upgrade 